### ISSUE TITLE
sliding with mouse scroll - request

### ISSUE THREAD

**Issue by diomed** [jlantunez/webslides#1]
this desperately needs possibility to slide right and left with mouse scroll wheel.

**Comment by jlantunez** [comment]
Totally agree! :) We're working on this for the next release. Thanks!

**Comment by stritti** [comment]
In addition, I think on mouse click would improve UX, too. (could be a little tricky with clickable elements).

**Comment by diomed** [comment]
@Belelros I've asked around and tested myself, this does not mouse-scroll on firefox, only on chrome.

**Comment by Belelros** [comment]
Which Firefox version are you using and which system? We've tested this and it seems to work.
