### ISSUE TITLE
Animation 'flashes' in Safari

### ISSUE THREAD

**Issue by ricardobeat** [jlantunez/webslides#10]
In the demo page (http://webslides.tv), after each slide finishes animation, the previous slide flashes for a single frame:

![webslides](https://cloud.githubusercontent.com/assets/97396/22005064/c203e16a-dc60-11e6-949c-0f6a0f7e473c.gif)

Browser version: Safari 10.0.2

**Comment by jlantunez** [comment]
Thanks, Ricardo. I hate Safari (touchpad, flashes, bounce...)
