### ISSUE TITLE
CSS sources

### ISSUE THREAD

**Issue by halian-vilela** [jlantunez/webslides#13]
Hi @jlantunez !

Thanks for this very nice piece of software!

I was wondering if you have some CSS source to use with a pre-processor? I use sass but less could be easily ported.

Maybe, if you don't have, I could make it... I'm planning to use webslides in my next project.

See ya!

**Comment by jlantunez** [comment]
Hi @halian-vilela, I'm old school. Please, do it! Thanks in advance :)

**Comment by CKGrafico** [comment]
@jlantunez I can help with that if you want

**Comment by Belelros** [comment]
Sure @CKGrafico we had this planned although slated for a later release. I've made an issue with some stuff: #52 Please ping me with any question.

**Comment by jlantunez** [comment]
@CKGrafico @Belelros  Let's do it :)
