### ISSUE TITLE
What about seeing a snippet of code in a pretty way?

### ISSUE THREAD

**Issue by vinimdocarmo** [jlantunez/webslides#17]
[Reveal.js](https://github.com/hakimel/reveal.js), another HTML presentation project, uses [highlight.js](https://github.com/isagalaev/highlight.js/) to highlight code syntax. Is there any plan to implement this feature in webslides?

**Comment by jlantunez** [comment]
Hi Vinícius, not at the moment. Who knows in the future :)

**Comment by vinimdocarmo** [comment]
I'm considering doing that and opening a pull request. Would it be an option?

**Comment by jlantunez** [comment]
Thanks so much, Vinícius :) Maybe in future releases. Right now I'm focused on what's most important.

**Comment by vinimdocarmo** [comment]
OK, @jlantunez. Thanks for your time.

**Comment by CKGrafico** [comment]
@jlantunez is it easy to create a plugin or something to help with that?

**Comment by Belelros** [comment]
You definitely could although from my understanding there's no need for that. You can have your snippets and use highlight to deal with them. WebSlides will take care of the presentation side unless there's something else I'm missing?

@CKGrafico @vinimdocarmo

**Comment by CKGrafico** [comment]
@Belelros Ouch, yes haha I'm trying to say something to help other people that need that easily not only how to add highlights js

**Comment by Belelros** [comment]
The reason we don't want to add Highlight.js or anything for that matter is that everyone has their preference and it's something you can add/change and it doesn't necessarily have to do with WebSlides nor with the presentational side of it.

Writing a plugin for it would be the same as calling it out of the plugin. The only thing that would change is the order of execution.

**Comment by vinimdocarmo** [comment]
You're totally right, @Belelros. In spite of my initial question, now I also think that there is no need to add this feature into WebSlides nor create a plugin. It's absolutely plausible to use highlight.js or any other tools that meet that requirement without any modification to the implementation of WebSlides itself.
