### ISSUE TITLE
how to do an animation before going to the next slide? 

### ISSUE THREAD

**Issue by kenvernaillenvub** [jlantunez/webslides#21]
How can I do an animation (like 'fade'), before going to the next slide?

Like fragments in reveal.js

**Comment by jlantunez** [comment]
Hi,

One easy solution is to add the animate.css library [animate.css library](https://github.com/daneden/animate.css) and edit:

section  * { } - base.css (line 1,396)

**Comment by nnals** [comment]
@kenvernaillenvub were you able to accomplish something similar to [fragments](http://lab.hakim.se/reveal-js/#/fragments)? if yes, how did you do it? thank you

**Comment by kenvernaillenvub** [comment]
@nnals I think I ended up using revealjs with css from webslides ^^
