### ISSUE TITLE
Slide overview 

### ISSUE THREAD

**Issue by gaborcsardi** [jlantunez/webslides#23]
This is imo one of the best features of  https://shwr.me/

I have not idea how challenging it is technically for webslides.

**Comment by ramon-src** [comment]
Depends... We can use the existings sections to separate them into this layout. Minimize the content into it or create a frame...

**Comment by jlantunez** [comment]
Let's keep it simple. Let's fix bugs first before implementing new features. Thanks in advance. I'm just a CSS guy :)

- Back and forward buttons on browser 
- Smooth touchpad/Mouse navigation 
- Safari flashes

**Comment by vivaxy** [comment]
Is it possible to implement this feature now?
