### ISSUE TITLE
IE11 needs a refresh with F5

### ISSUE THREAD

**Issue by vuwer** [jlantunez/webslides#29]
When watching https://webslides.tv/ in IE11 (latest with auto update) on Win7 I have to refresh every slide with F5 to view the slide.

Thank you, the software works great on FF or Chrome.

**Comment by Belelros** [comment]
I've checked this against 1.0.0 and it errors. After 19cd5bd seems _okayish_ although the behaviour is not perfect. Unsure of the level of support we're going to give to IE yet but it's definitely an improvement.

Will keep you posted!

**Comment by Belelros** [comment]
@vuwer this has been released now under 1.1.0. Please give it a shot and let us know how is it looking on your end.

**Comment by Belelros** [comment]
Closing as got no answer from @vuwer
