### ISSUE TITLE
How is it different/better than reveal.js?

### ISSUE THREAD

**Issue by karimsa** [jlantunez/webslides#30]
Hi, there!

As an avid user of Reveal.js, I was just wondering what sets apart WebSlides from [reveal.js](https://github.com/hakimel/reveal.js).

**Comment by jlantunez** [comment]
Hi Karim,

Reveal.js and slides.com are two wonderful tools. WebSlides is a solution for making presentations, landings, portfolios, and long-forms. It's a starting point for building custom CSS frameworks:

- A friendly markup
- 120+ predesigned slides
- 500+ SVG icons
