### ISSUE TITLE
Autoslide?

### ISSUE THREAD

**Issue by Taapo** [jlantunez/webslides#39]
I haven't checked the library too deeply yet, but is an autoslide feature available?

**Comment by jlantunez** [comment]
Hi Taapo,

maybe in the future :)

**Comment by marckrejci** [comment]
+1 for this feature. Would love to utilize webslides for digital wayfinding screens!

**Comment by jlantunez** [comment]
We've added autoslide :) Check out demo/why-webslides.html

**Comment by marckrejci** [comment]
Awesome, thx! :)
