### ISSUE TITLE
Auto Slide Feature

### ISSUE THREAD

**Issue by 2braincells2go** [jlantunez/webslides#43]
Firstly, great project guys!

I like the new auto slide feature of why-webslides.html

After few experiments cannot seem to get slide to stop advancing when mouse over (or touch event). Is there a simple way to have slides stop advancing when mouse over or at least click?

Thanks and cheers!

Woody

**Comment by jlantunez** [comment]
Hi Woody,

Not yet. We take note :)

**Comment by 2braincells2go** [comment]
Good deal, thank you.

**Comment by Belelros** [comment]
Hey @2braincells2go we're not sure we're going to implement this behaviour as there are a lot of use cases and limitations. For instance, mouse over stopping if you're on fullscreen and you don't have any more screens is going to be troublesome. 

We do offer functions `play` and `stop` to control that behaviour so you can adapt it to your needs.  To achieve what you want on click this should work:

```javascript
document.getElementById('webslides').addEventListener('click', function(){
  if (ws.interval_) { // Is playing
    ws.stop();
  } else {
    ws.play();
  }
});
```

You can always read our [technical docs](https://github.com/jlantunez/webslides/blob/master/docs/technical.md) to get more information. Please let us know your thoughts on this!

**Comment by 2braincells2go** [comment]
Thank you @Belelros .

Will be  a few days before get back to testing. Will give your code a try.

Cheers!
