### ISSUE TITLE
How to lower resistance between slides?

### ISSUE THREAD

**Issue by samyoungnyc** [jlantunez/webslides#44]
Great library - I was wondering if there's a place in the code to lower the resistance between the slides? I've taken a look but couldn't find a place where this setting could be customized.

**Comment by Belelros** [comment]
Hey @samyoungnyc it's not possible at the moment in a clean way (that is, passing an option). However we're thinking on ways to better configure plugins.

In the meantime, you can change this [variable](https://github.com/jlantunez/webslides/blob/master/static/js/webslides.js#L1264). If you provide a lower number, the resistance will be less.

**Comment by samyoungnyc** [comment]
Thanks for the tip - however I don't see any place in that file where there's a number assigned to that variable. I see `MouseEvent` on `ln. 888` & `ln. 1264` - is the value set elsewhere?

Thanks

**Comment by Belelros** [comment]
Sorry, it changed to this location: https://github.com/jlantunez/webslides/blob/master/static/js/webslides.js#L1336

**Comment by samyoungnyc** [comment]
Thanks I'll try that out

**Comment by samyoungnyc** [comment]
Hi - I'm a bit confused again - the version of webslides.js that I'm linking my HTML too has only 497loc - it starts like this: 

`/*==================================================================
Name: WebSlides
Version: 0.1.1 (trackpad gestures and keyboard shortcuts).
Date: 2017-02-11
Description: HTML presentations made easy.
URL: https://github.com/jlantunez/WebSlides
Thanks @LuisSacristan for your help :)
-
Based on SimpleSlides, by Jenn Schiffer:
https://github.com/jennschiffer/SimpleSlides
==================================================================== */`

Should I replace that file with the file you linked to?

**Comment by Belelros** [comment]
Hey. Yes! We've updated WebSlides quite a lot fixing some bugs and allowing for new behaviour. You can check that out on our Releases: https://github.com/jlantunez/webslides/releases

Note that there's a link to download all the demos and the .js with each recent release (from 1.0.0 onwards).

Please let me know if you do find any issues.

**Comment by Belelros** [comment]
This has now been fixed on [1.2.0](https://github.com/jlantunez/webslides/releases/tag/1.2.0)

**Comment by samyoungnyc** [comment]
Thanks it worked
