### ISSUE TITLE
Sliding with Page up and Page down

### ISSUE THREAD

**Issue by thoppe** [jlantunez/webslides#6]
Similar to #1 , it would be nice to use `Page Up` and `Page Down` to advance the slides. Many USB presentation auto advancers use these keystrokes to navigate. Bonus points for allowing the user to set the button(s) to advance and go back.

**Comment by jlantunez** [comment]
Check again ;)
![webslides-vertical](https://cloud.githubusercontent.com/assets/2033183/21961595/21881ab0-db0e-11e6-93da-d735dffd66cf.png)
