### ISSUE TITLE
Make navigation visible on mouse move

### ISSUE THREAD

**Issue by hvsh** [jlantunez/webslides#9]
I think it will be better ux if the navigation was visible on mouse move rather than having to hover over an invisible area to make it visible

**Comment by jlantunez** [comment]
Thanks for your suggestion.  Edit line 1521:

***Remove:
#navigation:hover {
opacity: 1;
}

***Add this:
#webslides:hover #navigation {
opacity: 1;
}

**Comment by hvsh** [comment]
jose that wasnt a question, that was a suggestion to you. I can make css modifications myself =D

**Comment by jlantunez** [comment]
Done!
